# Generated by Django 5.2.1 on 2025-07-10 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_validuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='validuser',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validuser',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validuser',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
