# Generated by Django 5.2.1 on 2025-07-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_validuser_attempt_validuser_progress_validuser_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validuser',
            name='name',
            field=models.CharField(default='Jane Doe', max_length=225),
            preserve_default=False,
        ),
    ]
