# Generated by Django 5.2.1 on 2025-07-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_validuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='validuser',
            name='awknowledge',
            field=models.BooleanField(default=False),
        ),
    ]
